language: r
cache: packages
r:
    - release

sudo: false

branches:
    only:
        - master

env:
    - NOT_CRAN=false

install: true

r_packages:
    - Rcpp
    - RcppArmadillo

script:
    - lscpu
    - Rscript Test/irisTest.R
