language: r
cache: packages
r:
    - release

pandoc: false

sudo: false

branches:
    only:
        - master

install: true

script:
    - lscpu
    - Rscript Test/irisTest.R
    - Rscript Test/orthantTest.R
