language: r
cache: packages
r:
    - release

sudo: false

branches:
    only:
        - master

install: true
r_packages: 
   - covr
   - data.table
   - ellipse
   - ggplot2
   - klaR
   - MASS
   - mda
   - mgcv
   - mlbench
   - MLmetrics
   - ModelMetrics
   - nnet
   - pamr
   - party
   - pls
   - proxy
   - randomForest
   - RANN
   - rARPACK
   - reshape2
   - spls
   - subselect
   - superpc
   - testthat
   - xgboost
   - Rcpp
   - RcppArmadillo

after_success:
    - lscpu
    - Rscript Test/irisTest.R
