language: r
cache: packages
r:
    - release

sudo: false

branches:
    only:
        - master

env:
    - NOT_CRAN=false

install:
    - Rscript Test/installPackages.R

script:
    - lscpu
    - Rscript Test/irisTest.R
